spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: dictHikariCP
    driverClassName: com.mysql.jdbc.Driver
    password: root
    username: root
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/rbac?characterEncoding=utf8&allowMultiQueries=true&useSSL=false
  batch:
    initialize-schema: always
